[project]
name = "pipe-detect-prod-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "altair<5",
    "pandas>=3.0.0",
    "pytz>=2025.2",
    "streamlit>=1.19.0",
    "ultralytics>=8.4.8",
]
