roi_loadcell:
- - 687
  - 320
- - 947
  - 326
- - 1295
  - 444
- - 871
  - 452
roi_caster5_origin:
- - 126
  - 65
- - 110
  - 261
- - 370
  - 280
- - 376
  - 82
roi_left_origin:
- - 13
  - 526
- - 77
  - 279
- - 6
  - 153
- - 3
  - 422
roi_right_origin:
- - 951
  - 284
- - 1791
  - 635
- - 1980
  - 250
- - 1129
  - 126
roi_safety_critical:
- - 101
  - 118
- - 447
  - 126
- - 1183
  - 873
- - 11
  - 869
roi_gate1_closed:
- - 13
  - 290
- - 443
  - 306
- - 433
  - 435
- - 25
  - 446
roi_gate1_open:
- - 2
  - 279
- - 121
  - 280
- - 113
  - 472
- - 3
  - 471
roi_gate2_closed:
- - 20
  - 424
- - 454
  - 444
- - 461
  - 628
- - 8
  - 617
roi_gate2_open:
- - 3
  - 425
- - 120
  - 421
- - 115
  - 717
- - 9
  - 723
