roi_loadcell:
- - 1177
  - 321
- - 1478
  - 458
- - 1728
  - 432
- - 1406
  - 311
roi_caster5_origin:
- - 307
  - 344
- - 612
  - 332
- - 557
  - 74
- - 244
  - 70
roi_left_origin:
- - 0
  - 119
- - 192
  - 282
- - 88
  - 780
- - 0
  - 712
roi_right_origin:
- - 1406
  - 260
- - 2497
  - 725
- - 2606
  - 12
- - 1443
  - 14
roi_safety_critical:
- - 154
  - 1116
- - 1058
  - 1109
- - 991
  - 29
- - 166
  - 25
roi_gate1_closed:
- - 180
  - 291
- - 673
  - 289
- - 684
  - 434
- - 186
  - 469
roi_gate1_open:
- - 141
  - 328
- - 317
  - 321
- - 315
  - 495
- - 131
  - 493
roi_gate2_closed:
- - 160
  - 481
- - 837
  - 456
- - 847
  - 678
- - 162
  - 727
roi_gate2_open:
- - 158
  - 487
- - 342
  - 481
- - 293
  - 1034
- - 119
  - 1036
