roi_loadcell:
- - 1234
  - 323
- - 1556
  - 499
- - 1920
  - 461
- - 1564
  - 262
roi_caster5_origin:
- - 999
  - 336
- - 635
  - 368
- - 632
  - 94
- - 962
  - 86
roi_left_origin:
- - 10
  - 209
- - 555
  - 203
- - 358
  - 942
- - 0
  - 982
roi_right_origin:
- - 1461
  - 182
- - 2424
  - 737
- - 2608
  - 747
- - 2604
  - 119
roi_safety_critical:
- - 577
  - 96
- - 1064
  - 92
- - 1314
  - 1114
- - 553
  - 1208
roi_gate1_closed:
- - 528
  - 379
- - 1058
  - 336
- - 1066
  - 442
- - 528
  - 512
roi_gate1_open:
- - 532
  - 381
- - 698
  - 370
- - 671
  - 508
- - 524
  - 520
roi_gate2_closed:
- - 385
  - 536
- - 1171
  - 461
- - 1191
  - 614
- - 430
  - 876
roi_gate2_open:
- - 379
  - 532
- - 671
  - 506
- - 653
  - 1007
- - 373
  - 1064