roi_loadcell:
- - 1195
  - 515
- - 1353
  - 745
- - 1817
  - 747
- - 1577
  - 510
roi_caster5_origin:
- - 645
  - 500
- - 896
  - 500
- - 896
  - 278
- - 651
  - 263
roi_left_origin:
- - 336
  - 873
- - 554
  - 363
- - 15
  - 303
- - 6
  - 905
roi_right_origin:
- - 1919
  - 822
- - 1598
  - 494
- - 2052
  - 402
- - 2070
  - 809
roi_safety_critical:
- - 444
  - 1288
- - 614
  - 274
- - 987
  - 305
- - 1427
  - 1307
roi_gate1_closed:
- - 533
  - 473
- - 1000
  - 477
- - 1006
  - 629
- - 550
  - 649
roi_gate1_open:
- - 517
  - 512
- - 687
  - 508
- - 683
  - 637
- - 514
  - 633
roi_gate2_closed:
- - 523
  - 649
- - 1164
  - 666
- - 1172
  - 882
- - 529
  - 927
roi_gate2_open:
- - 382
  - 658
- - 629
  - 666
- - 600
  - 1154
- - 311
  - 1156

