roi_loadcell:
- - 6
  - 145
- - 61
  - 143
- - 62
  - 211
- - 9
  - 209
roi_caster5_origin:
- - 12
  - 229
- - 61
  - 231
- - 63
  - 287
- - 18
  - 283
roi_left_origin:
- - 24
  - 314
- - 62
  - 309
- - 62
  - 365
- - 26
  - 364
roi_right_origin:
- - 23
  - 384
- - 65
  - 387
- - 65
  - 447
- - 27
  - 447
roi_safety_critical:
- - 157
  - 18
- - 158
  - 429
- - 622
  - 418
- - 619
  - 25
roi_gate1_closed:
- - 1
  - 10
- - 48
  - 10
- - 41
  - 93
- - 4
  - 83
roi_gate1_open:
- - 69
  - 13
- - 121
  - 16
- - 120
  - 79
- - 70
  - 74
roi_gate2_closed:
- - 84
  - 156
- - 138
  - 147
- - 141
  - 209
- - 92
  - 214
roi_gate2_open:
- - 93
  - 241
- - 124
  - 243
- - 126
  - 294
- - 97
  - 288
