roi_loadcell:
- - 928
  - 313
- - 1247
  - 441
- - 1538
  - 416
- - 1239
  - 300
roi_caster5_origin:
- - 249
  - 66
- - 591
  - 66
- - 609
  - 309
- - 255
  - 313
roi_left_origin:
- - 75
  - 853
- - 216
  - 244
- - 13
  - 118
- - 11
  - 834
roi_right_origin:
- - 1254
  - 253
- - 2334
  - 808
- - 2364
  - 66
- - 1305
  - 13
roi_safety_critical:
- - 272
  - 41
- - 154
  - 949
- - 1656
  - 969
- - 634
  - 41
roi_gate1_closed:
- - 204
  - 296
- - 645
  - 278
- - 673
  - 414
- - 208
  - 411
roi_gate1_open:
- - 199
  - 308
- - 356
  - 304
- - 368
  - 431
- - 193
  - 431
roi_gate2_closed:
- - 167
  - 424
- - 881
  - 409
- - 894
  - 634
- - 176
  - 705
roi_gate2_open:
- - 92
  - 435
- - 392
  - 428
- - 345
  - 964
- - 69
  - 956
